const auction = {
    id: 64,
    status: 'current',
    title: 'Spring 2020 Auction',
    date: {
        date: '2020-06-01',
        display: 'May 3-10, 2020',
        displayAbbrev: 'May 3-10, 2020',
    },
    description: '<p>LAMA\'s timed May 3-10, 2020 Online Only Auction featured 30 hand-selected works from Peter Alexander, Lita Albuquerque, John Baldessari, Sam Durant, Frank Romero, Ed Ruscha, Andy Warhol, and more. Top-selling lots included two Peter Alexander paintings (Combo 32 and Lancaster), Lita Albuquerque\'s 1975 Ereimul Series #4, Carlos Almaraz\'s City Bridge, and Frank Romero\'s The Closing of Whittier Boulevard.&nbsp;</p>\n<p><a href="/auctions/2020/06/1/results">See prices realized here</a></p>',
    lots: [
        {
            id: 35001,
            number: 1,
            title: 'Florence Tour',
            estimate_low: '$4,000',
            estimate_high: '$6,000',
            date: '1980; published 1981',
            medium: 'Art, the greatest Italian food, and beautiful views.',
            artist: '10 days',
            images: {
                small: 'Lot-small-001.png',
                large: 'Lot-large-001.png',
            },
            category: 'Fine Art',
        },
        {
            id: 35002,
            number: 2,
            title: 'Havana Tour',
            estimate_low: '$3,000',
            estimate_high: '$5,000',
            date: '1993',
            medium: 'Travel back in time and experience the rich culture, food, and natural beauty.',
            artist: '15 days',
            images: {
                small: 'Lot-small-002.png',
                large: 'Lot-large-002.png',
            },
            category: 'Fine Art',
        },
        {
            id: 35003,
            number: 3,
            title: 'Reykjavik Tour',
            estimate_low: '$4,000',
            estimate_high: '$6,000',
            date: '2001-2003',
            medium: 'View natural wonders from waterfalls and geysers to wild ponies and glaciers.',
            artist: '11 days',
            images: {
                small: 'Lot-small-003.png',
                large: 'Lot-large-003.png',
            },
            category: 'Fine Art',
        },
        {
            id: 35004,
            number: 4,
            title: 'Kyoto Tour',
            estimate_low: '$2,500',
            estimate_high: '$3,500',
            date: '1988',
            medium: 'Visit historic ryokans, experience the rich historic culture of Japan and eat the greatest food.',
            artist: '14 days',
            images: {
                small: 'Lot-small-004.png',
                large: 'Lot-large-004.png',
            },
            category: 'Fine Art',
        },
        {
            id: 35005,
            number: 5,
            title: 'Los Angeles Tour',
            estimate_low: '$2,500',
            estimate_high: '$3,500',
            date: '2001',
            medium: 'Hikes, food, entertainment, and parties.',
            artist: '6 days',
            images: {
                small: 'Lot-small-005.png',
                large: 'Lot-large-005.png',
            },
            category: 'Fine Art',
        },
        {
            id: 35006,
            number: 6,
            title: 'Melbourne Tour',
            estimate_low: '$2,000',
            estimate_high: '$3,000',
            date: '1989',
            medium: 'Hikes, surfing, snorkeling, and partying.',
            artist: '18 days',
            images: {
                small: 'Lot-small-006.png',
                large: 'Lot-large-006.png',
            },
            category: 'Fine Art',
        },
        {
            id: 35007,
            number: 7,
            title: 'New York Tour',
            estimate_low: '$1,000',
            estimate_high: '$1,500',
            date: '1981',
            medium: 'Fine and performing arts, world class food, and bars.',
            artist: '5 days',
            images: {
                small: 'Lot-small-007.png',
                large: 'Lot-large-007.png',
            },
            category: 'Fine Art',
        },
        {
            id: 35008,
            number: 8,
            title: 'Paris Tour',
            estimate_low: '$800',
            estimate_high: '$1,200',
            date: '1991',
            medium: 'The City of Lights has the greatest culture, food, art, and style in the world.',
            artist: '12 days',
            images: {
                small: 'Lot-small-008.png',
                large: 'Lot-large-008.png',
            },
            category: 'Fine Art',
        },
        {
            id: 35009,
            number: 9,
            title: 'Santorini Tour',
            estimate_low: '$1,500',
            estimate_high: '$2,000',
            date: '1985',
            medium: 'Island hopping, yachts, mediterranean cuisine, and beautiful architecture.',
            artist: '16 days',
            images: {
                small: 'Lot-small-009.png',
                large: 'Lot-large-009.png',
            },
            category: 'Ceramics',
        },
        {
            id: 35010,
            number: 10,
            title: 'Thailand Islands Tour',
            estimate_low: '$1,000',
            estimate_high: '$1,500',
            date: '1984',
            medium: 'Visit some of the most beautiful natural wonders in the world.',
            artist: '18 days',
            images: {
                small: 'Lot-small-010.png',
                large: 'Lot-large-010.png',
            },
            category: 'Fine Art',
        },
    ]
}

export default auction;